# This YAML is the default template and can be modified based on this 
---
version: 2.0
steps:
  PRE_BUILD:
  - checkout:
      name: "checkout"
      inputs:
        scm: "codehub"
        url: "git@codehub.devcloud.cn-east-3.huaweicloud.com:42b369588d84469d95d7b738fc58da8e/LakeSoul/for-nanhang.git"
        # branch: "merge_main"
        lfs: false
        submodule: false
  BUILD:
  - sh:
      name: "sh"
      inputs:
        command: "echo hello"
